on:
  schedule:
    - cron: "0 */24 * * *" # every 24 hours
  push:
    branches:
      - master
jobs:
  publish:
    permissions: read-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Generate README.md
        uses: teoxoy/profile-readme-stats@v2
        with:
          token: ${{ secrets.USER_TOKEN }}
      - name: Update README.md
        env:
          GH_TOKEN: ${{ secrets.USER_TOKEN }}
        run: |
          git config --global user.name github-actions[bot]
          git config --global user.email 41898282+github-actions[bot]@users.noreply.github.com
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git
          if [[ "$(git status --porcelain)" != "" ]]; then
            git add .
            git commit -m "Update README"
            git push
          fi
